sudo: false
language: java
jdk:
  - oraclejdk8

before_script:
  # install maven
  - mvn -N io.takari:maven:0.5.0:wrapper -Dmaven=3.5.2
  # instal mill
  - wget "https://raw.githubusercontent.com/lefou/millw/master/millw" -O millw && chmod +x millw

script:
  # Build with maven
  - ./mvnw clean install source:jar javadoc:jar
  # Build with mill
  - ./millw -i main.test.test
  - ./millw -i main.publishLocal
