= Domino Java - A Java DSL to master OSGi dynamics
:latest-version: 0.3.0
:link-github: https://github.com/domino-osgi/domino-java

ifdef::env-github[]
image:https://badges.gitter.im/Join%20Chat.svg["Gitter chat", link="https://gitter.im/domino-osgi/domino-java"]
endif::[]

This project tries to bring the comfort of the proven https://github.com/domino-osgi/domino[Domino Scala DSL] into the Java world.
It make most sense with at least Java 8 an it's closures, but on request, I can try to publish a Java7 (and older) compatible variant.

== Download

The latest version is {latest-version} and can be downloaded from http://search.maven.org/#search|ga|1|g%3A%22com.github.domino-osgi%22[Maven Central].

Maven::
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>com.github.domino-osgi</groupId>
  <artifactId>domino-java</artifactId>
  <version>{latest-version}</version>
</dependency>
----

Mill::
[source,scala,subs="attributes"]
ivy"com.github.domino-osgi:domino-java:{latest-version}"


Gradle::
[source,groovy,subs="attributes"]
implementation 'com.github.domino-osgi:domino-java:{latest-version}'



== Documentation

* https://javadoc.io/doc/com.github.domino-osgi/domino-java/0.3.0/index.html[Javadoc for latest domino-java version]
* https://gitter.im/domino-osgi/domino-java[Gitter chat]

== Building and Contributing

This project is build with the https://mill-build.com[Mill Build Tool]. 
If you don't have Mill installed, you can use the `./mill` script in this repository.

Publishing is now automized via GitHub Actions.

If you found a bug please {link-github}/issues[report it].
You can open a {link-github}/pull[pull request] or discuss and ask questions in the {link-github}/discussions[Discussions].

== Changelog

=== domino-java 0.3.0 - 2019-05-13

* Support multipe `OsgiContext.whenBundleActive` calls

=== domino-java 0.2.0 - 2018-08-03

* Added `ServiceWatching.whenServicePresent` with 4 types
* Updated major version of dependency de.tototec.utils.functional
* No longer re-export de.tototec.utils.functional

=== domino-java 0.1.1 - 2018-02-27

* Added `OsgiContext.isActive` method
* Log un-registrations of services
* Created test suite based on Felix Connect (aka PojoSR)

=== domino-java 0.1.0 - 2018-02-12

* Initial Release
