= Domino Java - A Java DSL to master OSGi dynamics
:latest-version: 0.3.0

ifdef::env-github[]
image:https://badges.gitter.im/Join%20Chat.svg["Gitter chat", link="https://gitter.im/domino-osgi/domino-java"]
endif::[]

This project tries to bring the comfort of the proven https://github.com/domino-osgi/domino[Domino Scala DSL] into the Java world.
It make most sense with at least Java 8 an it's closures, but on demand, I can try to publish a Java7 (and older) compatible variant.

== Download

The latest version is {latest-version} and can be downloaded from http://search.maven.org/#search|ga|1|g%3A%22com.github.domino-osgi%22[Maven Central].

Maven::
[source,xml,subs="attributes,verbatim"]
----
<dependency>
  <groupId>com.github.domino-osgi</groupId>
  <artifactId>domino-java</artifactId>
  <version>{latest-version}</version>
</dependency>
----

Gradle::
[source,groovy,subs="attributes"]
implementation 'com.github.domino-osgi:domino-java:{latest-version}'


mill::
[source,scala,subs="attributes"]
ivy"com.github.domino-osgi:domino-java:{latest-version}"



== Documentation

* https://domino-osgi.github.io/domino-java/javadoc/current[Javadoc for latest domino-java version]
* https://domino-osgi.github.io/domino-java/javadoc/0.1.x/[Javadoc for domino-java 0.1.x]
* https://gitter.im/domino-osgi/domino-java[Gitter chat]

== Changelog

=== domino-java 0.3.0 - 2019-05-13

* Support multipe `OsgiContext.whenBundleActive` calls

=== domino-java 0.2.0 - 2018-08-03

* Added `ServiceWatching.whenServicePresent` with 4 types
* Updated major version of dependency de.tototec.utils.functional
* No longer re-export de.tototec.utils.functional

=== domino-java 0.1.1 - 2018-02-27

* Added `OsgiContext.isActive` method
* Log un-registrations of services
* Created test suite based on Felix Connect (aka PojoSR)

=== domino-java 0.1.0 - 2018-02-12

* Initial Release
