on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [11, 17]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - run: ./mill __.compile + __.test + __.publishLocal --localIvyRepo testrepo

  publish:
    needs: [build]
    if: github.repository == 'domino-osgi/domino-java' && (startsWith( github.ref, 'refs/tags/') || (github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' ) )

    runs-on: ubuntu-latest
    concurrency: publish-{{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      # - name: Setup GPG secrets for publish
      #   run: |
      #     gpg --version
      #     cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
      #     gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        run: ./mill -i --import "ivy:com.lihaoyi::mill-contrib-sonatypecentral:" mill.contrib.sonatypecentral.SonatypeCentralPublishModule/publishAll --publishArtifacts __.publishArtifacts
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASS }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.GPG_SECRET_KEY }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
